#!/bin/bash                                                                                                                                                                                                      
                                                                                                                                                                                                                 
echo -n > statistics.log                                                                                                                                                                                         
                                                                                                                                                                                                                 
for i in {1..2}; do                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                              
    job_id=$(qsub mpi_task.pbs)                                                                                                                                                                                  
    echo "run $job_id"                                                                                                                                                                                           
                                                                                                                                               
    while true; do                                                                                                                                                                                               
        if qstat | grep -q "$job_id"; then                                                                                                                                                                       
            sleep 5                                                                                                                                                                                              
        else                                                                                                                                                                                                     
            break                                                                                                                                                                                                
        fi                                                                                                                                                                                                       
    done                                                                                                                                                                                                         
    echo "finished checking"                                                                                                                                                                                                                                                                                                                                   
done                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                
echo "Final node process statistics:"                                                                                                                                                                            
cat statistics.log
